#!/bin/sh
set -eu

envsubst '${BACKEND_HOSTPORT} ${CONTAINER_SERVICE_HOSTPORT} ${ROUTE_SERVICE_HOSTPORT} ${FLEET_SERVICE_HOSTPORT} ${CITIZEN_SERVICE_HOSTPORT} ${SENSOR_SERVICE_HOSTPORT} ${REPORTING_SERVICE_HOSTPORT} ${NOTIFICATION_SERVICE_HOSTPORT} ${ANALYTICS_SERVICE_HOSTPORT}' \
  < /etc/nginx/wastewise.conf.template \
  > /etc/nginx/conf.d/default.conf